### ISSUE TITLE
Question: What about Project Gutenberg as an alternative source?

### ISSUE THREAD

**Issue by ghost** [sgraaf/Replicate-Toronto-BookCorpus#5]
https://www.gutenberg.org/wiki/Gutenberg:Information_About_Robot_Access_to_our_Pages

**Comment by sgraaf** [comment]
I appreciate the suggestion! I looked into this myself previously (per [Google's suggestion](https://github.com/google-research/bert#pre-training-data)), but consider it beyond the scope of this repository. I say this because this repository serves as a means of creating a *faithful* replica of the original TBC dataset, which cannot be accomplished with books from Project Gutenberg (mostly because the books on Project Gutenberg are (understandably) old, and thus their writing styles are old/dated).
